project:
  type: website
  output-dir: docs

website:
  title: "Lee McCoy"
  # reader-mode: true
  # repo-url: https://github.com/leemccoy/leemccoy.github.io
  # repo-actions: [edit, issue]
  site-url: https://leemccoy.github.io/
  favicon: images/favicon/light-sage-chick.png
  google-analytics: 
    tracking-id: "G-SH7WN66KRS"
    anonymize-ip: true
  navbar:
    title: false
    logo: images/logos/shanny-csik-logo-transparent-dark.png
    logo-alt: "The name 'sam shanny-csik' written in green text. Above 'csik' is a green horizontal line, above which sits a green chick icon."
    right:
      - href: index.qmd
        text: home
      - about.qmd
  #    - href: projects.qmd
  #      text: projects
  #    - posts.qmd
      - text: get in touch!
        menu:
          # - icon: "{{< iconify simple-icons bluesky >}}"
          #   text: Bluesky
          #   href: https://bsky.app/profile/samcsik.bsky.social
          #   target: _blank
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/in/leemccoy/
            target: _blank
          - icon: envelope
            text: email
            href: mailto:electleemccoy@hotmail.com
      - icon: github
        href: https://github.com/leemccoy/leemccoy.github.io
        target: _blank
  page-footer: 
    background: light
    left: © 2026 Lee McCoy
    right: Website built with [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/leemccoy/leemccoy.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank}, [Quarto](https://quarto.org/){target=_blank}, and resources from [Sam Csik](https://ucsb-meds.github.io/creating-quarto-websites/)
format:
  html:
    page-layout: full
    sidebar: false
    theme: 
      - styles.scss
    mainfont: Nunito
    toc: true


